- asterisk/Containerfile
Fix for odbc errors.
Before the patch:
```
Apr 04 15:51:47 dn1 nethvoice8[91512]: [Apr  4 15:51:47] WARNING[1]: res_odbc.c:571 load_odbc_config: Unable to load config file res_odbc.conf
Apr 04 15:51:48 dn1 nethvoice8[91512]: [Apr  4 15:51:48] ERROR[1]: loader.c:2508 load_modules: res_odbc declined to load.
Apr 04 15:51:48 dn1 nethvoice8[91512]: [Apr  4 15:51:48] ERROR[1]: loader.c:2508 load_modules: Declined modules which depend on res_odbc: res_config_odbc, cel_odbc, cdr_adaptive_odbc, cdr_odbc, func_odbc
```
After the patch:
```
Apr 04 15:54:53 dn1 nethvoice8[93456]: [2023-04-04 15:54:53] NOTICE[1]: res_odbc.c:697 load_odbc_config: Registered ODBC class 'asteriskcdrdb' dsn->[MySQL-asteriskcdrdb]
```
> asterisk: add asterisk18-addons-mysql

- asterisk/Containerfile
- asterisk/entrypoint.sh
- asterisk/usr/bin/backup_astdb
- asterisk/usr/bin/restore_astdb
- imageroot/actions/configure-module/30traefik
- imageroot/actions/configure-module/71reports_api
- imageroot/actions/configure-module/72reports_ui
- imageroot/actions/configure-module/80start_services
- imageroot/actions/create-module/05setenvs
- imageroot/actions/create-module/80process_notifier
- imageroot/actions/restore-module/20copyenv
- imageroot/actions/restore-module/21database
- imageroot/actions/restore-module/22asterisk
- imageroot/actions/restore-module/70configure_module
- imageroot/actions/restore-module/71reload_services
- imageroot/bin/module-cleanup-state
- imageroot/bin/module-dump-state
- imageroot/etc/state-include.conf
Edits:
- Moved MariaDB service start from module creation to module configuration
- Added custom asterisk scripts for backup and restore of SQLite (I/O redirect in `podman exec` causes a lot of issues)
- NS8 configuration
- Added binaries for dump/cleanup
- Added module-restore action
- Added state-include.conf
Closes #61
> NS8 Backup and Restore

- build-images.sh
* `^/nethvoice$` --> `/nethvoice/`
* `^/freepbx/?$` --> `/freepbx/admin/`
* `^/freepbx/wizard$` --> `/freepbx/wizard/`
* `^/freepbx/visualplan$` --> `/freepbx/wizard/visualplan/`
fix #40
> fix(build, freepbx): Fix redirects

- imageroot/actions/destroy-module/60sip_proxy
Before try to remove the proxy's route check if the variable NETHVOICE_HOST was set by the `configure-module` action
> destroy-module: check if nethvoice's domain is set

- imageroot/actions/configure-module/30traefik
Tancredi API are called by nethcti-server or by phones, both calls it in HTTP and shouldn't be redirected to HTTPS because 
- nethcti-server is local
- if phones use HTTP is because they couldn't use HTTPS
> Disable tancredi http2https

- imageroot/actions/configure-module/60sip_proxy
- tests/00_nethvoice_install_dependencies.robot
- tests/10_nethvoice_actions/10_configure_integrations.robot
The proxy and the instance of the NethVocie module are in the same node, for correct routing, kamailio needs the destination address of the route to be the same as the address from where the SIP traffic is aspected.
nethesis/ns8-nethvoice#100
> configure-module: fix proxy's route address

- freepbx/entrypoint.sh
The original fix was made before the merge Asterisk and FreePBX
containers, it is no longer needed,
Original commit: https://github.com/nethesis/ns8-nethvoice/commit/43fbd1b60a92fc56f48f83bfc0e5e6be17c387b0
> freepbx: fix broken ca certs path

- imageroot/actions/get-facts/10get_facts
- tests/10_nethvoice_actions/10_get-facts_integrations.robot
The `get-facts` action will collect metrics about the NethVoice module. Currently, the exposed metrics are:
- `nethvoice_users_count`: Number of main extensions created
- `nethvoice_mobile_users_count`: Number of main extensions with the mobile app enabled
#127
> actions: add `get-facts` action

- imageroot/actions/configure-module/20setenvs
- imageroot/actions/configure-module/80start_services
If the values of the input attributes are different from the values stored in the associated environment variables, the relative services will be restarted.
Currently checked attributes:
* `nethvoice_host`
* `reports_international_prefix`
* `timezone`
> configure-module: restart services when needed

- imageroot/update-module.d/20restart
Avoid starting services that are not fully configured.
> update-module.d: restart only running services

- freepbx/Containerfile
Fix Stir/Shaken refactor
See: https://github.com/asterisk/asterisk/releases/tag/18.22.0
> freepbx: update to asterisk 18.22.0

- freepbx/initdb.d/migration.php
- mariadb/docker-entrypoint-initdb.d/30_nethcti3.user_nethlink-schema.sql
- nethcti-server/entrypoint.sh
Reference: https://github.com/nethesis/ns8-nethvoice/issues/154
NethCTI Server changes: https://github.com/nethesis/nethcti-server/pull/309
> nethlink. created user_nethlink table

- freepbx/usr/local/bin/import-certificate
Asterisk certificate and key were installed as root, but FreePBX reload fails if owner of those file isn't asterisk
> Fix Asterisk certificate owner

- imageroot/systemd/user/reports-redis.service
The `/data` volume defined in the upstream `redis` image is not used and it creates an orphanage anonymous volume every service restart. Also, anonymous volumes are not supported by the NS8 move/clone procedure.
https://github.com/nethesis/ns8-nethvoice/issues/171
> systemd: ignore image volumes on `reports-redis`

- imageroot/update-module.d/10env
`PROXY_IP` and `PROXY_PORT` variables are created by the `configure-module` action. In case of an update from a version where those variables were not present, we have to create them during the update procedure.
> update-module.d: set proxy's parameters variables

- freepbx/initdb.d/initdb.php
- freepbx/initdb.d/migration.php
To support the NAT topology, the outbound proxy's URI must have the `;lr` (Loose Routing) parameter.
nethesis/ns8-nethvoice#156
> freepbx: update outbound_proxy parameter format

- imageroot/events/nethvoice-proxy-settings-changed/00validate_event
- imageroot/events/nethvoice-proxy-settings-changed/20configure_proxy
- imageroot/events/nethvoice-proxy-settings-changed/80start_services
When the FQDN, IP, or port of the proxy are changed, update the
environment variables, adjust the proxy route, and restart freepbx and
tancredi services.
> events: update proxy configuration

- imageroot/actions/configure-module/30traefik
- imageroot/actions/configure-module/validate-input.json
- imageroot/actions/destroy-module/20destroy
- imageroot/actions/destroy-module/80cleanup_user_domain
- ui/src/views/Settings.vue
If the user's domain provider is external, it's not possible to manage the users directly, and the user manager portal is not available. So the following changes are made:
* Create the user manager HTTP rule only if the service is available.
* Don't request the admin's account provider credentials as mandatory.
* On module destroy, don't fail if an HTTP route doesn't exist or if the cleanup of account provider admin users is not possible.
> actions: support external users domain provider

- freepbx/entrypoint.sh
If it is a migration, some directories don't exist or have the wrong permissions
> Creates additional Asterisk directories

- imageroot/actions/configure-module/21subscription
Only set the subscription variable if it comes from `nsent`; otherwise, the credentials will not be valid to access additional external services.
> configure-module: check the type of subscription

- freepbx/Containerfile
This fix build failure because of asterisksounds.org being expired
> take asterisk audio files from github instead of asterisksounds

- nethcti-server/entrypoint.sh
On click of `/webrest/historycall/down_callrec/` post API inside CTI, server log returns this error: `Error: ENOENT: no such file or directory, open '/usr/lib/node/nethcti-server/plugins/com_static_http/static/`  it means that path is wrong, new path is `/app/plugins/com_static_http/static`
> nethcti-server. StaticPath: Fixed wrong static path

- imageroot/actions/clone-module/20start_mariadb_service
- imageroot/actions/clone-module/21set_mariadb_passwords
- imageroot/actions/clone-module/22set_db_services_ports
- imageroot/actions/clone-module/23stop_mariadb_service
- imageroot/actions/clone-module/30clean_env
- imageroot/actions/transfer-state/49stop_services
This pull request includes several improvements and fixes related to the module cloning process and state transfer procedures:
- **Reconfigured Service Ports:** Ensures that new service ports assigned after module cloning are correctly set in the database.
- **Environment Variable Cleanup:** Removes unnecessary environment variables as part of the module cloning process.
- **MariaDB Password Reset:** Resets the MariaDB passwords to ensure they are different from the original module instance after cloning.
- **Graceful Service Shutdown:** Ensures that NethVoice services are gracefully shut down before terminating the containers' volume transfer.
After the clone/move, the module must be reconfigured via `configure-module` to be fully operational. …
> Enhancements and Fixes for Module Cloning and State Transfer Procedures

- imageroot/systemd/user/freepbx.service
- imageroot/systemd/user/nethcti-server.service
The custom customer card templates will be stored in the `customer_card` volume, and the volume will be shared between the `freepbx` and `nethcti-server` containers.
https://github.com/nethesis/ns8-nethvoice/issues/263
> systemd: add customer_card volume

- freepbx/var/www/html/freepbx/admin/modules/nethcti3/functions.inc.php
In NethVoice CTI if the voicemail status is active the CF is to vmuXXX.
Added check if transfer recipient is voicemail in vmuXXX format because in that case the caller is incorrectly obtained.
> Change CF for CTI voicemail status

- mariadb/docker-entrypoint-initdb.d/50_asterisk.kvstore_Sipsettings.sql
Correctly terminate the SQL query in one of the database initialization scripts.
Typo introduced by PR: https://github.com/nethesis/ns8-nethvoice/pull/287.
> mariadb: fix missing semicolon

- imageroot/systemd/user/nethcti-server.service
In order for the change made in the PR to work: https://github.com/nethesis/nethcti-server/pull/316, need to add a TIMEZONE environment variable
> Added missing TIMEZONE variable inside nethcti-server unit

- freepbx/var/www/html/freepbx/rest/lib/csvimport.php
- freepbx/var/www/html/freepbx/rest/lib/libExtensions.php
- freepbx/var/www/html/freepbx/rest/modules/mainextensions.php
Instead of checking for userman syncing ad fail if it's locked, call the update low level function without checks.
If directory is syncing, it isn't possible to update extensions into userman table, so Wizard checks for userman directory lock before changing a mainextension. But syncing can take a lot of time and if there are a lot of users this make user page in wizard not usable.
Is lock checking really neded? If directory is locked, the [updateUser](https://github.com/FreePBX/userman/blob/e168ce938ff8d94b066a38e76478a7eb92cbee63/Userman.class.php#L2564) function [fails](https://github.com/FreePBX/userman/blob/e168ce938ff8d94b066a38e76478a7eb92cbee63/Userman.class.php#L2594) but why? In the cases of AD/LDAP, it shouldn't be really an issue because tue updateUser …
> remove checkUsermanIsUnlocked()

- freepbx/freepbx_init.sh
Launching reload with "-" simulate login so the environment isn't passed to the fwconsole reload. The subscription variables are in the environment and if they aren't seen by fwconsole qmanager assume the server isn't registered and disable qmanager
https://github.com/NethServer/dev/issues/7041
> Fix queue manager permission at startup

- imageroot/systemd/user/janus.service
Fix the reference to the `ICEIGNORE` environment variable in the Janus systemd service configuration.
https://github.com/NethServer/dev/issues/7023
> systemd: janus fix ICEIGNORE env var reference

- imageroot/actions/configure-module/validate-input.json
Increase the allowed length for report international prefixes to up to four digits.
https://github.com/NethServer/dev/issues/7043
> configure-module: allow 4-digit international prefix

- freepbx/freepbx_init.sh
- imageroot/systemd/user/freepbx.service
This is necessary with slow vps like Kaliweb that has too slow disk access that triggers the timeout
https://github.com/NethServer/dev/issues/7067
> Check Asterisk is running for 5 minutes intead of 30 seconds

- .github/workflows/label-pr-from-weblate.yml
Create a workflow to label PRs from Weblate with the `translation` label using `actions/labeler`, triggered on `pull_request` events.
> Add GitHub Actions workflow to label Weblate PRs

- .github/workflows/create-testing-release.yml
Add a new GitHub Action workflow that automatically creates testing releases when a pull request is merged into the main branch. The workflow:
- Triggers only on merged PRs to main branch
- Ignores changes to documentation and CI files
- Uses [gh-ns8-release-module](https://github.com/NethServer/gh-ns8-release-module) extension to create testing releases
> action: release module on PR merge to main

- imageroot/actions/restore-module/70configure_module
This pull request fixes an issue with the `configure-module` script where the `NETHVOICE_USER_PORTAL_PASSWORD` was missing. The fix ensures that the password is retrieved correctly from the `passwords.env` file.
refs:
- https://github.com/NethServer/dev/issues/7079
> Fix missing NETHVOICE_USER_PORTAL_PASSWORD in restore-module action

- imageroot/events/support-session-started/10add_support_user
- imageroot/events/support-session-stopped/10remove_support_user
- Add script to create support user upon session start (`10add_support_user`).
- Add script to remove support user upon session stop (`10remove_support_user`).
These scripts handle support user creation and deletion by interacting with the database, ensuring temporary users are managed appropriately for support sessions.
https://github.com/NethServer/dev/issues/7096
> feat: add support session user management scripts

- imageroot/actions/create-module/50mariadb-init
- imageroot/actions/import-module/40mysql
- imageroot/actions/restore-module/21database
- mariadb/docker-entrypoint-initdb.d/99_stop_mariadb_import.sh
The pull request includes several changes to the MariaDB initialization and module configuration scripts. the main is the init of mariadb during the create-module action
Overall, these changes improve the MariaDB initialization and module configuration process, making it more efficient and avoid to hit the systemd timeout for mariadb service on slow machine
https://github.com/NethServer/dev/issues/7078
> Avoid timeout on mariadb service initialization

- imageroot/actions/configure-module/61ice_enforce
- imageroot/actions/create-module/05setenvs
- imageroot/events/nethvoice-proxy-settings-changed/20configure_proxy
- imageroot/events/nethvoice-proxy-settings-changed/80start_services
- imageroot/systemd/user/janus.service
- imageroot/update-module.d/10env
- janus/README.md
This pull request adds the ability to enforce ICE candidates with the proxy IP
address. It introduces a new environment variable, `ICEENFORCE`, which is set
to the proxy IP address. The `janus.service` is also updated to include the
`--ice-enforce-list` option, allowing the enforcement of ICE candidates on
specific interfaces or IP addresses. Additionally, the `create-module` and
`update-module` actions are modified to include the `ICEENFORCE` variable
enforcement behavior.
https://github.com/NethServer/dev/issues/7099
> Implement ICE Enforcement Configuration

- freepbx/entrypoint.sh
- freepbx/etc/asterisk/freepbx_chown.conf
- freepbx/freepbx_init.sh
- Use asterisk user instead of root to install module at first start
- This should avoid random bug that prevent freepbx reload untill container is restarted
https://github.com/NethServer/dev/issues/7191
> fix(freepbx_init.sh): install  modules as asterisk user

- freepbx/entrypoint.sh
Change the owner of the volume `/var/lib/nethserver/nethcti/templates/customer_card` to `asterisk:asterisk` in the entrypoint. This ensures the NethVoice wizard can add new customer cards without permission issues.
https://github.com/NethServer/dev/issues/7219
> fix: set correct ownership for customer_card volume in entrypoint

- imageroot/systemd/user/freepbx.service
Resolve issue with environment variables containing special characters when
loaded via systemd. Adjusted `ExecStart` to invoke `podman` through `runagent`,
ensuring proper handling of systemd's variable parsing quirks.
https://github.com/NethServer/dev/issues/7254
> fix(systemd): fix env vars with special chars

- freepbx/initdb.d/migration.php
Ensures that the proxy is not added to the trunk named `identity0` for TIM trunks certification.
https://github.com/NethServer/dev/issues/7247
> fix(proxy): prevent adding proxy to trunk identity0 for TIM

- Containerfile
fwadm allows to open ports on install, but not on update  🤷‍♂️
https://github.com/NethServer/dev/issues/7323
> fix(sftp): Add portsadm permission on the node to open sftp port on update

- imageroot/update-module.d/20allocate_ports
If Flexisip was installed, there are 33 allocated port, but module can allocate [only 31](https://github.com/nethesis/ns8-nethvoice/blob/f1cfbe0471d5970b86b24b59618b389b85d4586a/Containerfile#L25) and the  agent.allocate_ports() fails
With this pr, a control is added and if there are still flexisip ports allocated, one of them is used for sftp
https://github.com/NethServer/dev/issues/7323
> fix(sftp): Fix port allocation if flexisip port was present

- imageroot/events/nethvoice-proxy-settings-changed/00validate_event
Ensure the `ICEENFORCE` environment variable is validated against the
`address` field in the service provider configuration. This fix prevents
false positives when determining if the proxy settings have changed.
https://github.com/NethServer/dev/issues/7345
> fix(events): validate ICEENFORCE in proxy settings

- freepbx/var/www/html/freepbx/rest/modules/provisioning-v2.php
Phones are configured to use or not TLS  by a switch on interface. The API doesn't triggered FreePBX retrieve config (apply changes) therfore if the phone is rebooted after making the change without doing any other change on interface, the new TLS configuration isn't applied
> fix(provisiong): Trigger retrieve when phone TLS config changes

- README.md
- imageroot/actions/configure-module/96publish_srv_keys
- imageroot/actions/create-module/30grants
- imageroot/actions/get-phonebook-credentials/20grant
- imageroot/actions/get-phonebook-credentials/40read
- imageroot/actions/get-phonebook-credentials/validate-output.json
- imageroot/update-module.d/30grants
- tests/10_nethvoice_actions/10_get_phonebook_credentials.robot
This PR allow access to the phonebook from other modules like WebTop.
See Copilot review for more info.
NethServer/dev#7261
Update an existing instance:
```
api-cli run update-module --data '{"module_url": "ghcr.io/nethesis/nethvoice:issue7261", "instances": ["nethvoice1"]}'
```
> feat: add pbookreader role, export phoenbook credentials

- build-images.sh
- freepbx/initdb.d/migration.php
- freepbx/wizard-ui/app/scripts/i18n/locale-en.json
- freepbx/wizard-ui/app/scripts/i18n/locale-it.json
- mariadb/docker-entrypoint-initdb.d/50_asterisk.rest_cti_macro_permissions_permissions.sql
- mariadb/docker-entrypoint-initdb.d/50_asterisk.rest_cti_permissions.sql
Create a new `all_groups` permission that allows to see all groups and operators.
- `all_groups` permission is granted to Base, Standard and Advanced profiles on existing installations for retrocompatibility: before the creation of the permission any user could see all groups
- `all_groups` permission is NOT granted to any profile on fresh installations of NethVoice
Ref:
- https://github.com/NethServer/dev/issues/7277
> fix: add permission to view all groups & operators

- freepbx/wizard-ui/app/scripts/controllers/configurations/profiles.js
- freepbx/wizard-ui/app/views/configurations/profiles.html
Profiles page: hide **Group X** permissions if **All groups** permission is enabled
Ref:
- https://github.com/NethServer/dev/issues/7277
> fix: show group permissions only if all_groups perm is off

- freepbx/wizard-ui/app/scripts/controllers/configurations/profiles.js
- freepbx/wizard-ui/app/views/configurations/profiles.html
- Hide switchboard operator permissions from Profiles page, i.e. those with a name starting with `in_queue_` and having description "Use this queue for Operator Panel incoming calls"
- Remove trailing spaces from source
Ref:
- https://github.com/nethserver/dev/issues/7366
> fix(profiles): hide switchboard operator permissions

- freepbx/Containerfile
mysql connector used in import phonebook python script is outdated. here is the correct version https://pypi.org/project/mysql-connector-python/
> feat(phonebook): update python mysql connector library

- freepbx/initdb.d/initdb.php
Environment variable for IAX is requested to NS and is also opend by firewall, but Asterisk IAX isn't binded to it
> fix(IAX): Set IAX2 port from environment variable

- imageroot/actions/configure-module/20setenvs
- imageroot/actions/configure-module/50users
- imageroot/actions/configure-module/60sip_proxy
- imageroot/actions/configure-module/61ice_enforce
- imageroot/actions/configure-module/80start_services
- imageroot/actions/configure-module/95service_adjust
Instead of dynamically composing the `RESTART_SERVICES` list, use a
fixed list in `80start_services`. Adjust nethcti-server handling
in `95service_adjust` to use a restart command rather than start.
Remove redundant asterisk restart logic to avoid potential conflicts
and ensure cleaner execution flow in the configuration module.
This simplifies the configuration and ensures services are reliably
restarted after changes.
https://github.com/NethServer/dev/issues/7258
> refactor: restart all services on configure

- freepbx/entrypoint.sh
- imageroot/actions/import-module/04initialize_volumes
May 05 09:39:52 makako asterisk_initialize_volumes[10509]: chown: cannot access '/var/lib/nethserver/nethcti/templates/customer_card': No such file or directory
May 05 09:39:52 makako agent@nethvoice21[7207]: chown: cannot access '/var/lib/nethserver/nethcti/templates/customer_card': No such file or directory
May 05 09:39:52 makako asterisk_initialize_volumes[10509]: [05-May-2025 09:39:52 UTC] PHP Notice:  Undefined index: NETHVOICE_MARIADB_PORT in /initdb.d/initdb.php on line 8
May 05 09:39:52 makako asterisk_initialize_volumes[10509]: [05-May-2025 09:39:52 UTC] PHP Notice:  Undefined index: AMPDBUSER in /initdb.d/initdb.php on line 9
May 05 09:39:52 makako asterisk_initialize_volumes[10509]: [05-May-2025 09:39:52 UTC] PHP Notice:  Undefined index: AMPDBPASS in /initdb.d/initdb.php on …
> fix(import): Avoid errors on import module

- imageroot/update-module.d/80restart
nethcti-server was correctly added to the service to restart when there aren't active calls, but wasn't removed from the services to restart immediately
https://github.com/NethServer/dev/issues/7442
> fix(update): restart nethcti-server when there aren't active calls

- imageroot/bin/restart-services-when-convenient
- imageroot/update-module.d/80restart
https://github.com/NethServer/dev/issues/7442
- restart all services when there are no calls instead of only a few
- restart all services together to avoid multiple restarts for services depending on others
- fix check of active calls if there is only one active call
> fix(update): restart service when there are no calls

- freepbx/entrypoint.sh
discussion: https://mattermost.nethesis.it/nethesis/pl/fcctu79jfib1u8xutfguyqeqmc
we cannot make GROK pattern when the color are written to log, we got something like this 
`May 20 14:57:56 VoipNethvoice freepbx[4165]: [2025-05-20 14:57:56] #033[1;33mNOTICE#033[0m[158]: #033[1;37mchan_sip.c#033[0m:#033[1;37m29058#033[0m #033[1;37mhandle_request_register#033[0m: Registration from '"1001" <sip:1001@93.42.2.141>' failed for '213.35.120.102:5819' - Wrong password`
and we would expect 
`May 20 14:57:56 VoipNethvoice freepbx[4165]: [2025-05-20 14:57:56] NOTICE[158]: chan_sip.c:29058 handle_request_register: Registration from '"1001" <sip:1001@93.42.2.141>' failed for '213.35.120.102:5819' - Wrong password`
Refs: https://github.com/NethServer/dev/issues/7481
> enhancement(logs): nocolor asterisk logs to improve pattern matching

- freepbx/entrypoint.sh
This PR enhances the resilience of the FreePBX container startup process.
It ensures that required directories are always present, preventing failures
when volumes are not mounted. Additionally, if database credentials are not
set, the script will now execute the provided command instead of exiting.
Both changes also address an issue encountered during the backup restore
procedure, where volumes are not mounted or database credentials are not
provided.
Also, the entrypoint now quietly removes an empty `cdr.conf` file, avoiding error
message if the file is missing.
https://github.com/NethServer/dev/issues/7513
> NethVoice, Improve FreePBX Entrypoint Robustness: Handle Missing Files, Directories, and DB Credentials

- freepbx/var/www/html/freepbx/admin/modules/nethcti3/functions.inc.php
With this pull request, proxy doesn't offer RTP encryption to extensions configured from wizard that has encryption switch turned off.
If such extensions are called, the isTrunk=1 header is added to the INVITE.
When INVITE has this header, Nethvoice proxy [doesn't offer encryption to the endpoint](https://github.com/nethesis/ns8-nethvoice-proxy/pull/11). Normally this isn't necessary because if the endpoint can't adopt encryption should renegotiate, but old endpoints suck
https://github.com/NethServer/dev/issues/7524
> feature(dialplan): Add isTrunk=1 on INVITES sent to phones without encryption

- imageroot/systemd/user/nethcti-ui.service
Add --health-cmd and --health-on-failure=kill options to the Podman run
command in the nethcti-ui systemd service. On healthcheck failure,
Podman kills the container, triggering a systemd service restart.
Default Podman healthcheck parameters:
- --health-start-period=0s
- --health-interval=30s
- --health-retries=3
With these defaults, the container is immediately marked as "starting"
at startup. The first healthcheck runs right away and may fail if the
application is not ready. The container remains in the "starting" state
until a healthcheck succeeds or the start period elapses (default 0s).
After three consecutive failed checks (one every 30 seconds), the
container is marked as "unhealthy". This means the application should be
ready within about 1 minute after startup to avoid being …
> feat(nethcti-ui): add Podman healthcheck

- imageroot/actions/create-module/21subscription
NethHotel and other features are blocked on configuration interface if NS8 doesn't have subscription, but the subscription variable is only written at configure. With this change, it's possible to enable subscription only features at first configuration.
> enhancement(subscription): Add subscription status before configuration

- freepbx/Containerfile
Adjust the COPY instruction to use the explicit target directory for
phonebooks.
https://github.com/NethServer/dev/issues/7564
> fix(freepbx): phonebooks copy path in Containerfile
