nethesis/ns8-nethvoice

imageroot/actions/configure-module/20setenvs
imageroot/actions/configure-module/30traefik
imageroot/actions/configure-module/validate-input.json

Forcing CORS Policy requirements through Traefik Proxy, adding additional CTI-UI domain to separate urls

Fixing CORS Policies for NethCTI Server

---

imageroot/actions/configure-module/30traefik
imageroot/actions/create-module/90firewall
imageroot/actions/destroy-module/20destroy
imageroot/systemd/user/janus.service
nethcti-server/README.md
nethcti-server/entrypoint.sh

Avoid error:
```
warn: [authentication] getting admin secret for authentication: /var/www/html/freepbx/wizard/scripts/custom.js does not exist
```

Multiple fixes

---

README.md
build-images.sh
imageroot/actions/configure-module/80start_services
imageroot/systemd/user/freepbx.service
imageroot/systemd/user/watcher.path
imageroot/systemd/user/watcher.service

https://github.com/orgs/nethesis/projects/7/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Linked+pull+requests%22%5D&pane=issue&itemId=24441744
See also https://github.com/nethesis/nethvoice-wizard-restapi/commit/afc1172bbb74a562c831a719830c5c631b0ce451

Add service notifier

---

build-images.sh
freepbx/var/www/html/freepbx/admin/libraries/BMO/Cron.class.php
imageroot/actions/configure-module/80start_services
imageroot/systemd/user/nethcti-server.service
imageroot/systemd/user/watcher.path
imageroot/systemd/user/watcher.service

The nethci-server can't start because some configuration files are missing

notifier: do not start nethcti-server at first boot

---

imageroot/systemd/user/mariadb.service
mariadb/docker-entrypoint-initdb.d/90_users.sh

https://github.com/nethesis/ns8-nethvoice/issues/33

Add permissions to read centralized phonebook to CTI user

---

build-images.sh
imageroot/systemd/user/janus.service

https://github.com/orgs/nethesis/projects/7/views/1?pane=issue&itemId=24272321

Janus certificates

---

build-images.sh

Ref: https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html

Debian sources moved to archive.debian.org

---

imageroot/actions/configure-module/60sip_proxy
imageroot/systemd/user/tancredi.service
tancredi/README.md
tancredi/entrypoint.sh

- configure-module: read proxy's fqdn
- tancredi: don't set proxy port
- tancredi: set proxy addr from environment variable
nethesis/ns8-nethvoice#104

Set proxy's domain in the phone provisioning

---

build-images.sh
renovate.json

Added renovatebot to automatically update nethvoice-cti dependency on build-images.sh file

build-images. added renovate to update nethvoice-cti dep

---

freepbx/entrypoint.sh
freepbx/etc/apache2/sites-enabled/000-default.conf
imageroot/actions/configure-module/30traefik

Use the domain root path to access the NethVoice interface

freepbx: redirect `/` to NethVoice wizard

---

imageroot/actions/configure-module/30traefik
imageroot/actions/destroy-module/20destroy
imageroot/events/service-users-admin-changed/00validate_event
imageroot/events/service-users-admin-changed/30traefik

- configure-module: set users-portal http route
- events: adjust users portal http route
https://github.com/nethesis/ns8-nethvoice/issues/135

Set users-portal http route

---

freepbx/initdb.d/migration.php

https://github.com/nethesis/ns8-nethvoice/issues/123

Migrate app extensions to Acrobit app format

---

freepbx/Containerfile
imageroot/systemd/user/nethcti-server.service
nethcti-server/Containerfile

https://github.com/nethesis/ns8-nethvoice/issues/132

add sound volume to  nethcti-server container

---

imageroot/actions/configure-module/20setenvs
imageroot/actions/configure-module/21subscription
imageroot/events/subscription-changed/10subscription
imageroot/events/subscription-changed/80sevice_restart

The credentials are used to authenticate on the phones' remote provisioning server.
nethesis/ns8-nethvoice#126

Get subscription credentials from the cluster

---

imageroot/actions/get-defaults/10defaults
imageroot/actions/get-defaults/validate-output.json
imageroot/systemd/user/flexisip.service
imageroot/systemd/user/janus.service
imageroot/systemd/user/mariadb.service
imageroot/systemd/user/nethcti-server.service
imageroot/systemd/user/nethcti-ui.service
imageroot/systemd/user/phonebook.service
imageroot/systemd/user/redis-flexisip.service
imageroot/systemd/user/reports-api.service
imageroot/systemd/user/reports-redis.service
imageroot/systemd/user/reports-ui.service
imageroot/systemd/user/tancredi.service
tests/10_nethvoice_actions/00_get_defaults_validation.robot
ui/public/i18n/en/translation.json
ui/public/i18n/it/translation.json
ui/src/views/Settings.vue

* https://github.com/nethesis/ns8-nethvoice/issues/120

Configure the timezone on the containers

---

imageroot/systemd/user/nethcti-server.service

https://github.com/nethesis/ns8-nethvoice/issues/125

Add SUBSCRIPTION_SYSTEMID and SUBSCRIPTION_SECRET to nethcti-server

---

imageroot/actions/configure-module/30traefik
imageroot/systemd/user/nethcti-ui.service

Make it easier to configure the nethlink client.
https://github.com/nethesis/ns8-nethvoice/issues/152

Access to CTI UI APIs endpoints via CTI's hostname

---

imageroot/actions/configure-module/60sip_proxy

Restart tancredi service when the domain of the proxy is changed
https://github.com/nethesis/ns8-nethvoice/issues/157

configure-module: restart tancredi service

---

tancredi/entrypoint.sh

https://github.com/nethesis/ns8-nethvoice/issues/157

Initialize Tancredi DEFAULTS array correctly

---

imageroot/systemd/user/janus.service

https://github.com/nethesis/ns8-nethvoice/issues/193

Fix Janus portrange syntax

---

ui/src/views/Settings.vue

To avoid errors when configuring the module, this PR checks the location of the selected domain and creates the `nethvoice-adm` user only if the domain is internal.

ui. create nethvoice-adm only if domain is internal

---

freepbx/Containerfile
freepbx/entrypoint.sh
freepbx/var/www/html/freepbx/rest/lib/libUsers.php
freepbx/var/www/html/freepbx/rest/modules/configuration.php
freepbx/var/www/html/freepbx/rest/modules/phonebook.php
freepbx/var/www/html/freepbx/rest/modules/settings.php
imageroot/systemd/user/freepbx.service

https://github.com/nethesis/ns8-nethvoice/issues/203

Fix phonebook csv upload

---

tancredi/Containerfile
tancredi/usr/share/tancredi/data/templates/nethesis-firmware.tmpl
tancredi/usr/share/tancredi/src/Entity/NethVoiceAuth.php

Vendoring the `master` branch, starting from
https://github.com/nethesis/nethserver-tancredi/commit/18a8a18bf0a78966f967fadf322e3c00bf5db49f
https://github.com/nethesis/ns8-nethvoice/issues/158

freepbx: import of `nethserver-tancredi` repo

---

phonebook/Containerfile
phonebook/README.md
phonebook/package-lock.json
phonebook/package.json
phonebook/phonebook.js

Vendoring the `ns8` branch, starting from
https://github.com/nethesis/nethserver-phonebook-mysql/commit/b5bccdbec1d72f88907fc9f02ec090bea2adf797
https://github.com/nethesis/ns8-nethvoice/issues/158

phonebook: import of `phonebook.js` code

---

imageroot/events/subscription-changed/80sevice_restart
imageroot/systemd/user/reports-api.service

https://github.com/nethesis/ns8-nethvoice/issues/207

Pass subscription environment to reports-api

---

freepbx/var/www/html/freepbx/rest/lib/libUsers.php
freepbx/var/www/html/freepbx/rest/modules/mainextensions.php

https://github.com/nethesis/ns8-nethvoice/issues/205

Limit configurable users in nethvoice wizard

---

ui/package.json
ui/public/i18n/en/translation.json
ui/public/i18n/it/translation.json
ui/src/views/Settings.vue
ui/yarn.lock

https://github.com/nethesis/ns8-nethvoice/issues/211#issuecomment-2139164921
**If the user starts to edit the hostname field, a warning message will be shown.**

settings. Show a warning message if user edit hostname

---

imageroot/bin/asterisk
imageroot/bin/fwconsole
imageroot/bin/mysql

Add some shortcuts that helps support to access useful commands from module home without having to login into containers

Add helpers to use some command from module shell as it was on 7

---

freepbx/configure_users.php
imageroot/actions/configure-module/50users

https://github.com/nethesis/ns8-nethvoice/issues/211

Cleanup extensions if domain has changed

---

freepbx/var/www/html/freepbx/rest/lib/libCTI.php

https://github.com/nethesis/ns8-nethvoice/issues/232

Skip queuemanager permission if not registered

---

freepbx/wizard-ui/app/scripts/controllers/configurations/profiles.js
freepbx/wizard-ui/app/scripts/controllers/routes/outbound.js
freepbx/wizard-ui/app/scripts/i18n/locale-en.json
freepbx/wizard-ui/app/scripts/i18n/locale-it.json
freepbx/wizard-ui/app/styles/trunks.css
freepbx/wizard-ui/app/views/configurations/profiles.html

https://github.com/nethesis/ns8-nethvoice/issues/232
**If user hasn't a valid enterprise license a notification will appear, and Queue Manager permission will come back to false**
**Added also a message in case of activation of: advanced recording, listen, intrude and recording**

Profiles. Added subscription control and privacy message

---

freepbx/var/www/html/freepbx/rest/modules/mainextensions.php
freepbx/wizard-ui/app/scripts/controllers/configurations/profiles.js

https://github.com/nethesis/ns8-nethvoice/issues/241

Profiles. Fixed missing queueManager permission update

---

freepbx/README.md
freepbx/initdb.d/migration.php

If trunks has the "custom" string in name, don't overwrite it's proxy configuration
https://github.com/nethesis/ns8-nethvoice/issues/249

Don't overwrite proxy of custom trunks

---

freepbx/wizard-ui/app/scripts/controllers/configurations/profiles.js
freepbx/wizard-ui/app/views/configurations/profiles.html

At the moment if a user has an active nethvoice subscription can't activate queueManager permission

Fix queue manager missing profile update if subscription active

---

freepbx/Containerfile
freepbx/freepbx_init.sh

Bulkdids module is unsupported and broken. Bulkhandler official module allows to create DIDs and more

Use Bulkhandler FreePBX module instead of bulkdids

---

freepbx/var/www/html/freepbx/rest/lib/csvimport.php

The code was missing during the import of the  `nethvoice-wizard-restapi` repository https://github.com/nethesis/ns8-nethvoice/pull/200

freepbx. csvimport: added missing nethlink

---

freepbx/Containerfile
freepbx/README.md
freepbx/entrypoint.sh
freepbx/etc/supervisor/conf.d/supervisord.conf
imageroot/bin/discover-smarthost
imageroot/events/smarthost-changed/10reload_services
imageroot/systemd/user/freepbx.service

https://github.com/nethesis/ns8-nethvoice/issues/250

Send voicemail emails using system smarthost configuration

---

freepbx/Containerfile
freepbx/freepbx_init.sh

create bulkhandler cache dir at buildtime

Bulkhandler cache

---

tancredi/Containerfile

Use a tag to download the source code instead of a moving branch
https://github.com/nethesis/ns8-nethvoice/issues/166

tancredi: install from a tag

---

freepbx/Containerfile

Use a tag to download the source code instead of a moving branch.
https://github.com/nethesis/ns8-nethvoice/issues/166

Install FreePBX forked modules from tags

---

freepbx/Containerfile

Use a tag to download the source code instead of a moving branch
https://github.com/nethesis/ns8-nethvoice/issues/166

freepbx: install FreePBX extraoptions from a tag

---

freepbx/Containerfile
freepbx/entrypoint.sh
freepbx/var/lib/asterisk/bin/send_email

add issues with first smarthost implementation:
- set the from address
- use local mail app
- allow no encryption
- allow no authentication
- don't send duplicate Date header
https://github.com/nethesis/ns8-nethvoice/issues/250

Set the from address and the mail command

---

ui/package.json
ui/public/i18n/en/translation.json
ui/src/views/Settings.vue
ui/yarn.lock

settings. Added warning notification on user domain change

---

ui/src/views/Settings.vue

settings. Store old user field value

---

freepbx/wizard-ui/app/scripts/controllers/configurations/profiles.js
freepbx/wizard-ui/app/views/configurations/profiles.html

nethvoiceCtiPermission. Missing post api on value switch

---

freepbx/Containerfile

Include pull request to fix error on MariaDB tinyint type 
https://github.com/FreePBX/music/pull/2
https://github.com/nethesis/ns8-nethvoice/issues/256

Update music module to 16.0.3

---

imageroot/events/user-domain-changed/20configure_ldap

- Fix typos in `user-domain-changed` event
- Reconfigure the user domain parameters, in the same way of the `configure-module` action
https://github.com/nethesis/ns8-nethvoice/blob/main/imageroot/actions/configure-module/50users

Fix `user-domain-changed` event

---

freepbx/configure_users.php
imageroot/actions/configure-module/10validate_user_domain

Safer check on ad domain string

---

nethcti-server/entrypoint.sh

https://github.com/NethServer/dev/issues/7022

Fixed wrong Nethvoice main page link

---

freepbx/wizard-ui/app/scripts/controllers/devices/models.js

https://github.com/NethServer/dev/issues/7006

Fixed missing custom models inside list

---

freepbx/README.md
freepbx/entrypoint.sh
imageroot/actions/create-module/05setenvs

https://github.com/NethServer/dev/issues/7022

Fix NethVoice documentations link

---

imageroot/update-module.d/10env

https://github.com/NethServer/dev/issues/7022

Fixed url link on module update

---

freepbx/Containerfile

https://github.com/NethServer/dev/issues/7000

Update Asterisk to 18.24.3

---

ui/src/views/Settings.vue

https://github.com/NethServer/dev/issues/7043

Fix report international prefix validator regexp

---

freepbx/var/www/html/freepbx/rest/modules/users.php
freepbx/wizard-ui/app/scripts/controllers/extensions.js
freepbx/wizard-ui/app/scripts/i18n/locale-en.json
freepbx/wizard-ui/app/scripts/i18n/locale-it.json
freepbx/wizard-ui/app/scripts/services/userservice.js
freepbx/wizard-ui/app/styles/main.css
freepbx/wizard-ui/app/views/extensions.html

API: add a GET that return true if userman is syncing
UI: add message to show syncing status
Reference: https://github.com/NethServer/dev/issues/7045

Add get /users/sync to wizard rest API

---

freepbx/var/www/html/freepbx/admin/modules/nethcti3/functions.inc.php

https://github.com/NethServer/dev/issues/7048

Write one line for each trunk when adding isTrunk header

---

imageroot/systemd/user/tancredi.service
tancredi/README.md

https://github.com/NethServer/dev/issues/7053
this affects also https://github.com/nethesis/ns8-nethvoice/pull/292

Add phonebook LDAP environment to Tancredi (used in entrypoint)

---

freepbx/entrypoint.sh
freepbx/usr/sbin/recallonbusy

This file exist since https://github.com/nethesis/ns8-nethvoice/releases/tag/0.0.1-rc.2.0.1 if NethVoice was installed before it doesn't exist
https://github.com/NethServer/dev/issues/7010

Create recallonbusy configuration file if it doesn't exist

---

freepbx/initdb.d/migration.php
freepbx/var/www/html/freepbx/rest/lib/gateway/functions.inc.php

https://github.com/NethServer/dev/issues/7056

fix primary gateway secret field length

---

freepbx/Containerfile

https://github.com/NethServer/dev/issues/7066

Update Asterisk to 18.25.0

---

freepbx/wizard-ui/app/scripts/controllers/devices/inventory.js

Add Nethesis NP-V61
https://github.com/NethServer/dev/issues/7032

Add Nethesis NP-V61

---

ui/src/views/Settings.vue

Reference: https://github.com/NethServer/dev/issues/7120

fix(ui): added missing var

---

nethcti-server/entrypoint.sh

Reference: https://github.com/NethServer/dev/issues/7118

feat(phone_urls): added cancel event

---

nethcti-server/entrypoint.sh

**Reference** : https://github.com/NethServer/dev/issues/7118
*See also* : https://support.yealink.com/en/portal/knowledge/show?id=64995b6b6a27da76bd071950#:~:text=Body%0Akey%3DOK-,Variable%20Values%20List,-Yealink%20phones%20also

fix(phone_urls): removed old yealink url

---

tancredi/Containerfile
tancredi/usr/share/tancredi/data/templates/nethesis-firmware.tmpl

https://github.com/NethServer/dev/issues/7216

feat(provisioning): Update Nethesis NP X5 phone firmware

---

build-images.sh

Reference: https://github.com/NethServer/dev/issues/7267

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.3.0

---

build-images.sh

Reference: NethServer/dev#7267

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.3.1

---

build-images.sh

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.3.2

---

freepbx/Containerfile
freepbx/freepbx_init.sh

https://github.com/NethServer/dev/issues/7269

feat(freepbx): Install asterisk-cli FreePBX module

---

freepbx/wizard-ui/app/scripts/controllers/configurations/preferences.js

**Reference:** https://github.com/NethServer/dev/issues/7259

fix: inconsisten status on 200 receive and null response on extensions

---

imageroot/systemd/user/nethcti-server.service

fix(nethcti-server): remove useless volume

---

tancredi/Containerfile

https://github.com/NethServer/dev/issues/7291

chore(tancredi): bump Tancredi to version 1.3.1

---

imageroot/systemd/user/sftp.service
imageroot/update-module.d/20allocate_ports

https://github.com/NethServer/dev/issues/7140

fix(sftp): Add port on update

---

imageroot/systemd/user/sftp.service

https://github.com/NethServer/dev/issues/7323

feat(sftp): Add also sounds volume to sftp container

---

freepbx/var/www/html/freepbx/admin/modules/nethcqr/agi-bin/nethcqr.php

https://github.com/NethServer/dev/issues/7330

fix(nethcqr): Answer() before asking for DTMF

---

imageroot/systemd/user/sftp.service
sftp/README.md

enhancement(sftp): Add spool volume and README

---

nethcti-server/entrypoint.sh

**Reference**: https://github.com/NethServer/dev/issues/7324

feat(nethcti-server): new token expiration

---

freepbx/entrypoint.sh
freepbx/etc/asterisk/freepbx_menu.conf

https://github.com/NethServer/dev/issues/7253

fix(freepbx): Show Asterisk Logfiles module on FreePBX

---

nethcti-server/entrypoint.sh

Reference:
- https://github.com/NethServer/dev/issues/7336

fix(interval): update entrypoint.sh

---

build-images.sh

https://github.com/NethServer/dev/issues/7336

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.4.1

---

freepbx/wizard-ui/app/scripts/controllers/devices/inventory.js
tancredi/Containerfile

https://github.com/NethServer/dev/issues/7314

Add NP-X5 v2

---

build-images.sh

https://github.com/NethServer/dev/issues/7148

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.6.1

---

tancredi/Containerfile

https://github.com/NethServer/dev/issues/7355

chore: update Tancredi to version 1.3.3

---

tancredi/Containerfile

https://github.com/NethServer/dev/issues/7361

chore: update Tancredi to version 1.3.4

---

build-images.sh

Reference:
- https://github.com/NethServer/dev/issues/7136

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.8.0

---

build-images.sh

**Reference**:
- https://github.com/NethServer/dev/issues/7136

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.8.1

---

freepbx/usr/sbin/recallonbusy

https://github.com/NethServer/dev/issues/7303

fix(recallonbusy): Use hints to define devices state instead of DeviceState

---

imageroot/events/service-users-admin-changed/30traefik
imageroot/events/user-domain-changed/20configure_ldap

Ref:
- https://github.com/NethServer/dev/issues/7156

fix: users-admin and user-domain-changed events

---

imageroot/update-module.d/10env

If missing, add `NETHCTI_PRIVACY_NUMBERS` env variabile while updating
Ref:
- https://github.com/nethserver/dev/issues/7363

fix: add NETHCTI_PRIVACY_NUMBERS env variable

---

freepbx/var/www/html/freepbx/rest/modules/provisioning-v2.php

https://github.com/NethServer/dev/issues/7151
- remove obsolete useless APIs
- add a new /phones/reconfigure POST that takes extension number as an argument
- POST send a SIP notify "generic-reload" to the phone (only if it is already registered)
- phone reload its configuration

feat(freepbx): API for triggering phones configuration reload

---

build-images.sh

References:
- https://github.com/NethServer/dev/issues/7313
- https://github.com/NethServer/dev/issues/7364

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.9.1

---

build-images.sh

References:
- https://github.com/NethServer/dev/issues/7364

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.9.2

---

build-images.sh

References:
- https://github.com/NethServer/dev/issues/7392
- https://github.com/NethServer/dev/issues/7338
- https://github.com/NethServer/dev/issues/7406

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.9.3

---

build-images.sh

Reference:
- https://github.com/NethServer/dev/issues/7341

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.9.5

---

build-images.sh

Reference:
- https://github.com/NethServer/dev/issues/7423

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.9.6

---

build-images.sh

**References**: 
- NethVoice CTI
- https://github.com/NethServer/dev/issues/7403
- Phone-Island
- https://github.com/NethServer/dev/issues/7393
- https://github.com/NethServer/dev/issues/7358

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.9.7

---

freepbx/freepbx_init.sh

Use array to add and remove module at startup instead of a list in the for to make code more flexible

feat(freepbx): Use array for module install/remove at startup

---

imageroot/bin/restart-services-when-convenient
imageroot/update-module.d/20restart
imageroot/update-module.d/80restart

https://github.com/NethServer/dev/issues/7442

On update, try-restart freepbx only if there aren't active calls

---

build-images.sh

**Reference**:
- https://github.com/NethServer/dev/issues/7368

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.10.0

---

tancredi/Containerfile

https://github.com/NethServer/dev/issues/7469

chore(tancredi): update Tancredi to version 1.3.5

---

freepbx/var/www/html/freepbx/rest/modules/physicalextensions.php

https://github.com/NethServer/dev/issues/7475

feat(API): POST and GET for extension displayname

---

freepbx/var/lib/asterisk/bin/send_email

fix(voicemail): fix when SMTP is configured to server itself

---

build-images.sh

**NethVoice CTI References**:
- https://github.com/NethServer/dev/issues/7171
- https://github.com/NethServer/dev/issues/7262
- https://github.com/NethServer/dev/issues/7317
- https://github.com/NethServer/dev/issues/7293
- https://github.com/NethServer/dev/issues/7137
- https://github.com/NethServer/dev/issues/7457
- https://github.com/NethServer/dev/issues/7483
- https://github.com/NethServer/dev/issues/7484
**Phone-Island References**:
- https://github.com/NethServer/dev/issues/7137
- https://github.com/NethServer/dev/issues/7473
- https://github.com/NethServer/dev/issues/7462

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.10.1

---

freepbx/var/www/html/freepbx/admin/modules/nethcti3/functions.inc.php
tancredi/Containerfile

feature(dialplan): Change SIP response for unregistered extensions
feature(dialplan): Add Answer() and Ringing() to macro-dial-one on CF
https://github.com/NethServer/dev/issues/7321

feature(dialplan): Make dialplan compliant with TIM requisites

---

freepbx/var/www/html/freepbx/admin/modules/nethhotel/htdocs/functions.inc.php

https://github.com/nethesis/neth-hotel/commit/e904ff8f7400270a38aad621f22517d828001870
https://github.com/NethServer/dev/issues/7425

fix(hotel): fix an hystorical typo

---

imageroot/actions/get-configuration/20read
ui/public/i18n/en/translation.json
ui/public/i18n/it/translation.json
ui/src/views/Settings.vue

Enable Hotel only if there is a Subscription
https://github.com/NethServer/dev/issues/7425

feat(hotel): Enable Hotel only if Subscription is enabled

---

freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/checkin.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/cleanRoom.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/configAlarm.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/extra.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/set-reception-lang.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/set-room-lang.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/svegliafallita.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/htdocs/functions.inc.php

https://github.com/NethServer/dev/issues/7425

fix(hotel): log to stderr to avoir stdout be taken by agi

---

build-images.sh

Reference:
- https://github.com/NethServer/dev/issues/7500

chore(deps): update ghcr.io/nethesis/nethvoice-cti to v0.10.3

---

imageroot/actions/configure-module/validate-input.json
ui/public/i18n/en/translation.json
ui/public/i18n/it/translation.json

https://mattermost.nethesis.it/nethesis/pl/pxedbfh1tfg3b8e7bhyta8agwr

fix(settings): Allow hostname, deny ipv4

---

freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/configAlarm.php
freepbx/var/www/html/freepbx/admin/modules/nethhotel/agi-bin/set-room-lang.php

https://github.com/NethServer/dev/issues/7425

fix(hotel): Minor fixes to queries

---

imageroot/update-module.d/85mysql_update

Reference:
- https://github.com/NethServer/dev/issues/7500

fix: remove old integration token

---

freepbx/var/lib/asterisk/bin/send_email

https://mattermost.nethesis.it/nethesis/pl/kg1zp5ce87rc78yfzftop36hgw
🐐

fix(voicemail): fix typo in StartTLS encryption

---

freepbx/wizard-ui/app/index.html
freepbx/wizard-ui/app/scripts/app.js

**Reference**: 
- https://github.com/NethServer/dev/issues/7268

fix: added missing streaming configuration page

---

build-images.sh

Reference:
- https://github.com/NethServer/dev/issues/7531

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.10.8

---

freepbx/var/www/html/freepbx/admin/modules/nethcti3/functions.inc.php

https://github.com/NethServer/dev/issues/7524

fix(INVITE): fix isTrunk=1 for extension regexp

---

build-images.sh

References:
- https://github.com/NethServer/dev/issues/7539
- https://github.com/NethServer/dev/issues/7531

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.11.0

---

freepbx/var/www/html/freepbx/admin/modules/nethhotel/htdocs/functions.inc.php

https://mattermost.nethesis.it/nethesis/pl/peysi88t9jyh7eixk4wui11gny

fix(hotel): avoid empty room checkin

---

freepbx/Containerfile

https://github.com/NethServer/dev/issues/7562

chores(freepbx): Update Queues module to upstream 16.0.28

---

freepbx/initdb.d/migration.php

https://github.com/NethServer/dev/issues/7606

fix(freepbx): use admin table for the migration status

---

build-images.sh

**Reference**: https://github.com/NethServer/dev/issues/7632

chore(deps): update ghcr.io/nethesis/nethvoice-cti docker tag to v0.11.5

---

build-images.sh

Reference:
- https://github.com/NethServer/dev/issues/7504
PR Reference:
- https://github.com/nethesis/nethcti-middleware/pull/2

chore: update nethcti-middleware for FreePBX APIs

---

imageroot/actions/clone-module/22set_db_services_ports

https://github.com/NethServer/dev/issues/7616

fix(freepbx): avoid error on clone when there are multiple IAX bindports
